version: "3.3"
services:
    rsk:
        image: khanhnb/rskj:dev
        # logging: *default-logging
        user: rsk
        entrypoint: "java -Dlogging.stdout=INFO -Dlogging=OFF -Dkeyvalue.datasource=rocksdb -Drpc.providers.web.cors=* -Drpc.providers.web.http.bind_address=0.0.0.0 -Drpc.providers.web.http.port=8545 -Drpc.providers.web.http.hosts.0=* -cp rsk.jar co.rsk.Start --regtest"
        volumes:
            - ./rsk:/var/lib/rsk/.rsk
        ports:
            - "8545:8545"
