PrivateKey = {Path = "/pk/dac-member.keystore", Password = "testonly"}

[L1]
WsURL = "ws://zkevm-mock-l1-network:8546"
RpcURL = "http://zkevm-mock-l1-network:8545"
PolygonValidiumAddress = "0x7D4d665B37d6b098913170d3B525d6BA4e6a8aAb"
DataCommitteeAddress = "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE"
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = "32"
GenesisBlock = "87"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "zkevm-data-node-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
