PrivateKey = {Path = "/pk/dac-member.keystore", Password = "testonly"}

[L1]
WsURL = "wss://rsk-rpc-ws-1.biteigen.xyz"
RpcURL = "https://rsk-rpc-1.biteigen.xyz"
PolygonValidiumAddress = "0xB03466839321dc06cCa69D602e89ea95f5340B68"
DataCommitteeAddress = "0x1F0B1D544c7C897Fd2E2aA99748c8195b191e15b"
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = "32"
GenesisBlock = "5284644"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "zkevm-data-node-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
